### ISSUE TITLE
英語版のREADMEを作成する

### ISSUE THREAD

**Issue by PeterTeng** [chocoby/jp_prefecture#21]
## WHY

海外の開発者が日本でサービスを立ち上げるときにも気軽に使えるようにしたい

## SOLUTION

- [x] Readme_enを作成し、現在のReadmeにリンク加える✅
- ~~既存Readmeを英語にし、別ファイルで日本語記述~~
-  ~~既存Readmeを日本語と英語にする~~
-  ~~Github Wikiをでガイド書く~~

**Comment by chocoby** [comment]
GitHub 的には既存 README が英語なのが望ましいですが、このライブラリは日本語ユーザーが多いと思いますので、「Readme_enを作成し、現在のReadmeにリンク加える」が良いかと思います。

**Comment by PeterTeng** [comment]
@chocoby その方針でWork in progress の Pull Request 出しました。確認をお願いします🙇
